### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by zhuangxiaohui** [sindresorhus/redent#3]
[This package](https://www.jsdelivr.com/package/npm/detect-indent) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by sindresorhus** [comment]
This is a problem with jsDelivr. You should open an issue on their repo. It's totally valid to not specify `main` field when the main file is named `index.js`.

**Comment by zhuangxiaohui** [comment]
The version you want to compile is the unedited version, which is not recognized by CND
